# frontend/.github/workflows/frontend.yml
name: Frontend CI

on:
  push:
    branches: [ main, development ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, development ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Run tests
      run: npm test -- --coverage --passWithNoTests --watchAll=false
      env:
        CI: true
    
    - name: Build application
      run: npm run build
    
    - name: Upload test coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '18.x'
      with:
        directory: ./frontend/coverage
        flags: frontend
        name: frontend-coverage