name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
        
    - name: Lint backend
      run: |
        cd backend
        npm run lint
        
    - name: Run backend tests
      run: |
        cd backend
        npm test

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Lint frontend
      run: |
        cd frontend
        npm run lint
        
    - name: Run frontend tests
      run: |
        cd frontend
        npm run test:ci
        
    # Comment out build step until more content is ready
    # - name: Build frontend
    #   run: |
    #     cd frontend
    #     npm run build

  integration-check:
    runs-on: ubuntu-latest
    # Add your integration tests here when ready